/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 src/assets/3d/sky.glb --printwidth 120 
Author: JABAMI Production (https://sketchfab.com/JabamiProduction)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/skybox-skydays-3-ec111b6006a14bfb91dee33a4646e80b
Title: Skybox Skydays 3
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/sky.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, -0.001, -Math.PI]}>
        <mesh
          geometry={nodes.SM_Skybox_MI_Skybox_v3_Inst_0.geometry}
          material={materials.MI_Skybox_v3_Inst}
          rotation={[-Math.PI, 0, 0]}
          scale={0.01}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/sky.glb')
