/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Dimitri Matcharashvili (https://sketchfab.com/ditomatch)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/low-poly-stylized-fruits-collection-f2f0f61bfba54a018db74ef4ccaffc8b
Title: Low-Poly Stylized Fruits Collection
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

import appleScene from '../assets/3d/apple.glb'
const Apple = (props) => {
  const { nodes, materials } = useGLTF(appleScene)
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.RedApple_RedApple_0.geometry}
          material={materials.RedApple}
          position={[-100, 50.357, 200]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={50}
        />
      </group>
    </group>
  )
}

export default Apple;