/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: lakonaas (https://sketchfab.com/lakonaasgmail)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/camping-17819b1a615c44f4a82e518450269f1c
Title: Camping
*/

import React, { useRef, useState } from "react";
import { useGLTF, useAnimations, Html, useCursor, Billboard } from "@react-three/drei";
import campingScene from "../assets/3d/camping.glb?url";

/** GLTF XZ for layout; centered on x=0, z=0; y fixed at 0.4. */
const ICOSPHERE_POSITIONS_RAW = [
  [4.219, 0.993, -0.669],
  [4.169, 1.001, 0.411],
  [3.107, 1.033, 0.295],
  [2.958, 1.048, -0.078],
  [3.058, 1.023, -0.23],
  [3.222, 0.984, -0.542],
  [3.482, 1.046, -0.739],
  [3.81, 1.01, -0.717],
  [4.002, 0.992, -0.624],
  [4.269, 1.058, -0.426],
  [3.931, 1.032, 0.418],
  [3.414, 1.055, 0.478],
  [4.237, 1.043, -0.148],
  [4.107, 1.012, 0.136],
  [3.669, 1.057, 0.502],
];
const _icosphereN = ICOSPHERE_POSITIONS_RAW.length;
const _icosphereCx =
  ICOSPHERE_POSITIONS_RAW.reduce((s, p) => s + p[0], 0) / _icosphereN;
const _icosphereCz =
  ICOSPHERE_POSITIONS_RAW.reduce((s, p) => s + p[2], 0) / _icosphereN;
const icospherePositionsCentered = ICOSPHERE_POSITIONS_RAW.map(([x, , z]) => [
  x - _icosphereCx,
  0.4,
  z - _icosphereCz,
]);

const Camping = (props) => {
  const group = useRef();
  const [hovered, setHovered] = useState(false);
  const { nodes, materials, animations } = useGLTF(campingScene);
  const { actions } = useAnimations(animations, group);
  useCursor(hovered);

  return (
    <group
      ref={group}
      {...props}
      dispose={null}
      onPointerOver={(e) => {
        e.stopPropagation();
        setHovered(true);
      }}
      onPointerOut={(e) => {
        e.stopPropagation();
        setHovered(false);
      }}
    >
      {hovered && (
        <Billboard position={[0, 1.5, 0]} follow>
          <Html
            center
            distanceFactor={14}
            style={{ pointerEvents: "none", width: "max-content", whiteSpace: "nowrap" }}
          >
            <div className="inline-block max-w-none whitespace-nowrap rounded-md bg-neutral-900/90 px-3 py-1 text-xs font-medium text-white shadow-md backdrop-blur-sm">
              Hi I'm Devin!
            </div>
          </Html>
        </Billboard>
      )}
      <group name="Sketchfab_Scene">
        <group
          name="Sketchfab_model"
          rotation={[-Math.PI / 2, 0, 0]}
          scale={1.178}
        >
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              {/* Fire */}
              <group name="Plane006_36" position={[0, 0.5, 0]}>
                <mesh
                  name="Object_121"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_121.geometry}
                  material={materials["Lamp.004"]}
                >
                  <meshBasicMaterial color="orangered" />
                </mesh>
              </group>
              {/* Rocks */}
              <group
                name="Icosphere035_54"
                position={icospherePositionsCentered[0]}
                rotation={[-0.854, -0.697, -0.156]}
                scale={[0.243, 0.097, 0.185]}
              >
                <mesh
                  name="Object_157"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_157.geometry}
                  material={materials["Material.077"]}
                />
              </group>
              <group
                name="Icosphere034_55"
                position={icospherePositionsCentered[1]}
                rotation={[-0.72, -0.502, 0.08]}
                scale={[0.243, 0.097, 0.185]}
              >
                <mesh
                  name="Object_159"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_159.geometry}
                  material={materials["Material.058"]}
                />
              </group>

              <group
                name="Icosphere031_58"
                position={icospherePositionsCentered[2]}
                rotation={[-1.081, -0.857, -0.478]}
                scale={[0.443, 0.177, 0.337]}
              >
                <mesh
                  name="Object_165"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_165.geometry}
                  material={materials["Material.077"]}
                />
              </group>

              <group
                name="Icosphere030_59"
                position={icospherePositionsCentered[3]}
                rotation={[-1.282, 0.206, 2.605]}
                scale={0.12}
              >
                <mesh
                  name="Object_167"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_167.geometry}
                  material={materials["Material.058"]}
                />
              </group>

              <group
                name="Icosphere029_60"
                position={icospherePositionsCentered[4]}
                rotation={[-2.865, -0.966, -1.827]}
                scale={0.112}
              >
                <mesh
                  name="Object_169"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_169.geometry}
                  material={materials["Material.058"]}
                />
              </group>
              <group
                name="Icosphere028_61"
                position={icospherePositionsCentered[5]}
                rotation={[-1.081, -0.857, -0.478]}
                scale={[0.33, 0.132, 0.251]}
              >
                <mesh
                  name="Object_171"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_171.geometry}
                  material={materials["Material.077"]}
                />
              </group>
              <group
                name="Icosphere027_62"
                position={icospherePositionsCentered[6]}
                rotation={[-1.218, -0.002, 1.996]}
                scale={0.147}
              >
                <mesh
                  name="Object_173"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_173.geometry}
                  material={materials["Material.058"]}
                />
              </group>
              <group
                name="Icosphere026_63"
                position={icospherePositionsCentered[7]}
                rotation={[-0.175, -0.467, 1.005]}
                scale={0.112}
              >
                <mesh
                  name="Object_175"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_175.geometry}
                  material={materials["Material.077"]}
                />
              </group>
              <group
                name="Icosphere025_64"
                position={icospherePositionsCentered[8]}
                rotation={[-0.995, -0.81, -0.361]}
                scale={[0.33, 0.132, 0.251]}
              >
                <mesh
                  name="Object_177"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_177.geometry}
                  material={materials["Material.058"]}
                />
              </group>
              <group
                name="Icosphere024_65"
                position={icospherePositionsCentered[9]}
                rotation={[-0.17, -0.413, 1.016]}
                scale={0.136}
              >
                <mesh
                  name="Object_179"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_179.geometry}
                  material={materials["Material.058"]}
                />
              </group>
              <group
                name="Icosphere023_66"
                position={icospherePositionsCentered[10]}
                rotation={[-0.995, -0.81, -0.361]}
                scale={[0.33, 0.132, 0.251]}
              >
                <mesh
                  name="Object_181"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_181.geometry}
                  material={materials["Material.077"]}
                />
              </group>
              <group
                name="Icosphere022_67"
                position={icospherePositionsCentered[11]}
                rotation={[-0.175, -0.467, 1.005]}
                scale={0.112}
              >
                <mesh
                  name="Object_183"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_183.geometry}
                  material={materials["Material.058"]}
                />
              </group>
              <group
                name="Icosphere021_68"
                position={icospherePositionsCentered[12]}
                rotation={[-1.282, 0.206, 2.605]}
                scale={0.12}
              >
                <mesh
                  name="Object_185"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_185.geometry}
                  material={materials["Material.058"]}
                />
              </group>
              <group
                name="Icosphere020_69"
                position={icospherePositionsCentered[13]}
                rotation={[-1.081, -0.857, -0.478]}
                scale={[0.33, 0.132, 0.251]}
              >
                <mesh
                  name="Object_187"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_187.geometry}
                  material={materials["Material.058"]}
                />
              </group>
              <group
                name="Icosphere019_70"
                position={icospherePositionsCentered[14]}
                rotation={[-0.17, -0.413, 1.016]}
                scale={0.112}
              >
                <mesh
                  name="Object_189"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_189.geometry}
                  material={materials["Material.058"]}
                />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
};

export default Camping;
