/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: PolyCube (https://sketchfab.com/ItsPolyCube)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/cute-mug-free-3d-model-c329807e8b354e3883d8e6a1596563ae
Title: Cute Mug - Free 3D model
*/

import React, { useState } from "react";
import { useGLTF, useCursor, Billboard, Html } from "@react-three/drei";

import coffeeScene from "../assets/3d/coffee.glb?url";

const Coffee = ({ onOpen, ...props }) => {
  const { nodes, materials } = useGLTF(coffeeScene);
  const [hovered, setHovered] = useState(false);
  useCursor(hovered);
  return (
    <group
      {...props}
      dispose={null}
      onPointerOver={(e) => {
        e.stopPropagation();
        setHovered(true);
      }}
      onPointerOut={(e) => {
        e.stopPropagation();
        setHovered(false);
      }}
      onClick={(e) => {
        e.stopPropagation();
        onOpen?.();
      }}
    >
      {" "}
      {hovered && (
        <Billboard position={[0, 2.25, 0]} follow>
          <Html
            center
            distanceFactor={14}
            style={{
              pointerEvents: "none",
              width: "max-content",
              whiteSpace: "nowrap",
            }}
          >
            <div className="inline-block max-w-none whitespace-nowrap rounded-md bg-neutral-900/90 px-3 py-1 text-xs font-medium text-white shadow-md backdrop-blur-sm border border-white">
                cafes i like
            </div>
          </Html>
        </Billboard>
      )}
      <group rotation={[-1.479, -0.062, 0.075]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_4.geometry}
            material={materials["Material.001"]}
            position={[0.042, -0.283, -0.055]}
            rotation={[-0.124, 0.209, 0.233]}
            scale={[1.148, 0.857, 1.148]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_6.geometry}
            material={materials["Material.003"]}
            position={[-0.2, 0.635, -0.065]}
            rotation={[-0.096, 0.223, 0.103]}
            scale={[0.939, 0.864, 0.939]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_8.geometry}
            material={materials["Material.001"]}
            position={[-1.41, -0.049, 0.226]}
            rotation={[-0.124, 0.209, 0.233]}
            scale={[0.149, 0.448, 0.121]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_10.geometry}
            material={materials["Material.006"]}
            position={[-0.395, 0.418, 0.935]}
            rotation={[-0.124, 0.209, 0.233]}
            scale={0.09}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_12.geometry}
            material={materials["Material.007"]}
            position={[0.146, 0.414, 1.003]}
            rotation={[-0.124, 0.209, 0.233]}
            scale={[0.184, 0.102, 0.158]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_14.geometry}
            material={materials["Material.006"]}
            position={[0.56, 0.623, 0.706]}
            rotation={[-0.124, 0.209, 0.233]}
            scale={0.09}
          />
        </group>
      </group>
    </group>
  );
};

export default Coffee;
