/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Ram Surya (https://sketchfab.com/ramsurya)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/low-poly-floating-island-9700497248364520bd2a9e61272d6b62
Title: Low-Poly Floating Island
*/

import { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import islandScene from "../assets/3d/low-poly_floating_island.glb?url";
import { a } from "@react-spring/three";

const Island = (props) => {
  const islandRef = useRef();

  const { nodes, materials } = useGLTF(islandScene);

  return (
    <a.group ref={islandRef} {...props}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.Object_2.geometry}
          material={materials.Material}
        />
        <mesh
          geometry={nodes.Object_3.geometry}
          material={materials.Material_1}
        />
        <mesh
          geometry={nodes.Object_4.geometry}
          material={materials.Material_3}
        />
        <mesh
          geometry={nodes.Object_5.geometry}
          material={materials.Material_2}
        />
        <mesh
          geometry={nodes.Object_6.geometry}
          material={materials.Material_7}
        />
        <mesh
          geometry={nodes.Object_7.geometry}
          material={materials.Material_4}
        />
        <mesh
          geometry={nodes.Object_8.geometry}
          material={materials.Material_5}
        />
        <mesh
          geometry={nodes.Object_9.geometry}
          material={materials.Material_6}
        />
        <mesh
          geometry={nodes.Object_10.geometry}
          material={materials.Material_8}
        />
      </group>
    </a.group>
  );
};

export default Island;
