/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 src/assets/3d/island.glb 
Author: Ram Surya (https://sketchfab.com/ramsurya)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/low-poly-floating-island-9700497248364520bd2a9e61272d6b62
Title: Low-Poly Floating Island
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import islandScene from '../assets/3d/island.glb'

const Island = (props) => {
  const { nodes, materials } = useGLTF(islandScene)
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_3.geometry} material={materials.Material_1} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.Material_2} />
      </group>
    </group>
  )
}

export default Island;